- hosts: all
  user: locthp
  become: true
  tasks:
  - name: simulate error
    shell: ls /test/
    register: command_result
    ignore_errors: true
  # - name: display error
  #   debug:
  #     msg:  "{{ command_result }}"

  
  # - name: Update cache the Ubuntu servers to be latest
  #   ansible.builtin.apt:
  #     update_cache: true
  #     force_apt_get: true
  #   when: ansible_distribution == "Ubuntu"
  #   async: 7200
  #   poll: 5
  #   register: command_result
  #   ignore_errors: true
  # - name: Upgrade the Ubuntu servers to be latest
  #   ansible.builtin.apt:
  #     force_apt_get: true
  #     upgrade: "yes"
  #   when: ansible_distribution == "Ubuntu"
  #   async: 3600
  #   poll: 5
  #   register: command_result
  #   ignore_errors: true

  
  - name: display error
    debug:
      msg:  "{{ command_result }}"
    changed_when: command_result.stderr != ""