- hosts: all
  user: locthp
  become: true
  tasks:
  - block:
    - name: simulate error
      shell: ls /test/
      register: command_result
    - name: "Run after error"
      debug:
        msg: "Hello World"
    rescue: 
    - name: display error
      debug:
        msg:  "{{ command_result }}"
      changed_when: command_result.stderr != ""
  - name: Run other task
    debug:
      msg: "Hello, this is other task"