- hosts: all
  become: true
  tasks:
  - name: update repos on CentOS
    yum: update_cache=true
    when: ansible_distribution == "CentOS"
  - name : install nginx on CentOS
    yum: name=nginx state=latest update_cache=true
    when: ansible_distribution == "CentOS"    
  - name: install httpd on CentOS
    yum: name=httpd state=latest update_cache=true
    when: ansible_distribution == "CentOS"


  - name: update repos on Ubuntu
    apt: update_cache=true
    when: ansible_distribution == "Ubuntu"
  - name : install nginx on Ubuntu
    apt: name=nginx state=latest update_cache=true
    when: ansible_distribution == "Ubuntu"
  - name: install apache2 on Ubuntu
    yum: name=apache2 state=latest update_cache=true
    when: ansible_distribution == "Ubuntu"

