- hosts: all
  become: true
  user: 'l.truong'
  tasks:
  - name: create user "ansible"
    user:
      name: ansible
      password: "$6$mysecretsalt$gIIYs0Xgc7sSQkH.zKaz8/AfaMomYzR1QZYtccwmJcUt8VpLq4D055UCCX4MlwgePOP80ZRwhppvBF72RIAVi/"
      uid: "1010"

  - name: add "ansible" user to sudoers
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0400


  - name: add authorized key to "ansible" user
    authorized_key:
      user: "ansible"
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE7VCs9jo31XMhIIB0x6dw8HyuEBwoW18yGCkkr0E1ag l.truong@locthp-lab-srv01"
