- name: copy default web page
  copy:
    src: default_site.html
    dest: "{{default_path_page}}/index.html"
    owner: root
    group: root
    mode: 0644
  register: nginx

- name: restart nginx service
  service:
    name: nginx
    state: restarted
  when: nginx.changed
