- hosts: all
  user: locthp
  become: true
  tasks:
  - name: Check diskspace usage of host
    shell: df -h | awk 'NR > 1 {print $6 $5}'
    when: ansible_distribution == "Ubuntu"
    register: result
  - name: Print the output of result
    debug:
         msg: "{{ item }}"
    with_items:
         - "{{ result.stdout_lines }}"