- hosts: all
  user: locthp
  become: true
  tasks:
  - name: Check diskspace usage of host
    shell: df -h | awk 'NR > 1 && $5+0 > 10 {print "fs usage at" " " "\x27" $6 "\x27" " " "is" " " $5}'
    when: ansible_distribution == "Ubuntu"
    register: result

  - name: Prepare body's content for each host
    ansible.builtin.set_fact:
        message: "there are filesystems on host {{ inventory_hostname }} which are using above 50% \n"

  - name: Append to message
    ansible.builtin.set_fact:
        message: "{{ message + item + '\n' }}"
    loop: "{{ result.stdout_lines }}"
  # - name: Process disk usage of each host
  #   processed_output: "{{ result.stdout_lines | list }}"

  - name: Print out the message
    debug:
         msg: "{{ message }}"

  - name: Send Discord message
    uri:
      url: "https://discordapp.com/api/webhooks/1234035793492705382/W8-AVHaXkOG2RjAO6ILK8rfibPAGYdDNU7VSBlg5pGtRry14QzKL9qFMARhsd3sLLYLo"
      method: POST
      body_format: json
      # body: '{"content": "Disk space on {{ inventory_hostname }} {{ result.stdout_lines }} is above 50%!"}'
      body:
        content: "{{ message | to_json }}"
      headers:
          Content-Type: application/json
      status_code: 204
