- hosts: all
  user: locthp
  become: true
  serial: 1
  tasks:
  - name: Check diskspace usage of host
    shell: df -h | awk 'NR > 1 && $5+0 > 10 {print "fs usage at" " " "\x27" $6 "\x27" " " "is" " " $5}'
    when: ansible_distribution == "Ubuntu"
    register: result
  # - name: Start the message
  #   ansible.builtin.set_fact:
  #       message: "-------------------------------------------------------------------------"   





  - name: Prepare body's content for each host
    ansible.builtin.set_fact:
        introduction: "there are filesystems on host {{ inventory_hostname }} which are using above 50% \n"

  
  # - name: Initialize message
  #   ansible.builtin.set_fact:
  #       message: [] 
  # - name: Append introduction into the message
  #   ansible.builtin.set_fact:
  #       message: " {{ message + [introduction] }} " 
  # - name: Append to message
  #   ansible.builtin.set_fact:
  #       message: "{{ message + [item] }}"
  #   loop: "{{ result.stdout_lines }}"

  - name: Initialize message
    ansible.builtin.set_fact:
      message: []

  - name: Append introduction into the message
    ansible.builtin.set_fact:
      message: "{{ message + [introduction] }}"

  - name: Append to message
    ansible.builtin.set_fact:
      message: "{{ message + [item] }}"
    loop: "{{ result.stdout_lines }}"

  - name: Print all messages for debugging
    debug:
      msg: "Host {{ inventory_hostname }}: {{ item }}"
    loop: "{{ ansible_play_batch | zip(message) }}"

  - name: Send Discord message
    uri:
      url: "https://discordapp.com/api/webhooks/1234035793492705382/W8-AVHaXkOG2RjAO6ILK8rfibPAGYdDNU7VSBlg5pGtRry14QzKL9qFMARhsd3sLLYLo"
      method: POST
      body_format: json
      body:
        content: "{{ item }}"
      headers:
          Content-Type: application/json
      status_code: 204
    loop: "{{ message }}"  
    loop_control:
      pause: 1

