- hosts: all
  user: locthp
  become: true
  serial: 1
  tasks:
  - name: Check diskspace usage of host
    shell: df -h | awk 'NR > 1 && $5+0 > 80 {print  "fs usage at" " " "\x27" $6 "\x27" " " "is" " " $5}'
    when: ansible_distribution == "Ubuntu"
    register: result


  - name: Prepare body's introductory content for each host
    ansible.builtin.set_fact:
        introduction: "there are filesystems on host {{ inventory_hostname }} which are using above 80% \n"
    when: result.stdout | default('') | length > 0

  - name: Initialize message
    ansible.builtin.set_fact:
      message: []
    when: result.stdout | default('') | length > 0

  - name: Set dashes
    ansible.builtin.set_fact:
        dashes: "-------------------------------------------------------------------------"  
    when: message is defined

  - name: Add upper dashes
    ansible.builtin.set_fact:
      message: "{{ message + [dashes] }}"
    when: message is defined
  
  - name: Append introduction into the message
    ansible.builtin.set_fact:
      message: "{{ message + [introduction] }}"
    when: message is defined


  - name: Append to message
    ansible.builtin.set_fact:
      message: "{{ message + [item] }}"
    loop: "{{ result.stdout_lines }}"
    when: message is defined
  
  - name: Add bottom dashes
    ansible.builtin.set_fact:
      message: "{{ message + [dashes] }}"
    when: message is defined


  - name: Send Discord message
    uri:
      url: "https://discordapp.com/api/webhooks/1234035793492705382/W8-AVHaXkOG2RjAO6ILK8rfibPAGYdDNU7VSBlg5pGtRry14QzKL9qFMARhsd3sLLYLo"
      method: POST
      body_format: json
      body:
        content: "{{ item }}"
      headers:
          Content-Type: application/json
      status_code: 204
    loop: "{{ message }}"
    loop_control:
      pause: 1
    when: message is defined
