- hosts: all
  user: locthp
  become: true
  tasks:
  - name: Check diskspace usage of host
    shell: df -h | awk 'NR > 1 && $5+0 > 50 {print $6 "\t" $5}'
    when: ansible_distribution == "Ubuntu"
    register: result

  # Notify to Discord
  - name: Print the output of result
    debug:
        msg: "{{ item }}"
    with_items:
          - "{{ result.stdout_lines }}"
