- hosts: all
  user: locthp
  become: true
  tasks:
  - name: Check diskspace usage of host
    shell: df -h | awk 'NR > 1 && $5+0 > 50 {print "fs usage at" " " "\x27" $6 "\x27" " " "is" " " $5}'
    when: ansible_distribution == "Ubuntu"
    register: result

  # - name: Print the output of result
  #   debug:
  #       msg: "{{ item }}"
  #   with_items:
  #         - "{{ result.stdout_lines }}"
  - name: Process disk usage of each host
    processed_output: "{{ result.stdout_lines | list }}"

  - name: Send Discord message
    uri:
      url: "https://discordapp.com/api/webhooks/1234035793492705382/W8-AVHaXkOG2RjAO6ILK8rfibPAGYdDNU7VSBlg5pGtRry14QzKL9qFMARhsd3sLLYLo"
      method: POST
      body_format: json
      body: '{"content": "Disk space on {{ inventory_hostname }} {{ item }} is above 50%!"}'
      headers:
          Content-Type: application/json
      status_code: 204
