- hosts: all
  user: locthp
  become: true
  tasks:
  - name: Check diskspace usage of host
    shell: df -h | awk 'NR > 1 {sub(/%/, "", $5); print $6 "\t" $5}'
    when: ansible_distribution == "Ubuntu"
    register: result
  - name: Process disk usage data
    ansible.builtin.set_fact:
       processed_output: "{{ result.stdout_lines | map('split', '\t') | select('int(item.1) > 80') | list }}"
  - name: Print the output of result
    debug:
        msg: "{{ processed_output }}"
  #   with_items:
  #        - "{{ result.stdout_lines }}"
  #   where: item

