- hosts: all
  user: locthp
  become: true
  tasks:
  - name: Update the Ubuntu servers to be latest
    apt:
      update_cache: true
      upgrade: full
    when: ansible_distribution == "Ubuntu"


  - name: Update the CentOS servers to be latest
    yum:
      update_cache: true
      name: "*"
      state: latest
    when: ansible_distribution == "CentOS"