- hosts: all
  user: locthp
  become: true
  gather_facts: yes
  tasks:
    - name: Display hostname and IP address
      debug:
        msg: "Hostname: {{ ansible_hostname }}, IP Address: {{ ansible_default_ipv4.address }}"
    - name: Check defined env
      debug:
        msg: ""{{ lookup('env','ANSIBLE_PERSISTENT_CONNECT_TIMEOUT') }} is an environment variable""