- hosts: all
  user: locthp
  become: true
  tasks:
  - name: Modify restart mode from interactive to list
    ansible.builtin.replace:
      path: /etc/needrestart/needrestart.conf
      regexp: "^\\#\\$nrconf{restart} = \\'i\\'\\;$"
      replace: "$nrconf{restart} = 'l';"
