- name: install nginx on all hosts
  package:
    update_cache: true
    name:
     - nginx
    state: latest

- name: start nginx service on CentOS only
  service:
    name: nginx
    state: started
    enabled: true
  when: ansible_distribution == 'CentOS'

